server:
    port: 8080
    servlet:
      context-path: /api/v1
spring:
  application:
    name: API-GATEWAY
  main:
    allowBeanDefinitionOverriding: true
#api gatewaysetting

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/api/v1/users/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/api/v1/hotels/**

      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/api/v1/ratings/**

#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# path




